name: Build Executable

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']


    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install Dependencies
      run: poetry install

    - name: Build Executable
      run: poetry run pyinstaller -p gitshield --add-data './pre-commit:.' --onefile --name gitshield-cli gitshield/cli.py

    - name: Add Executable Permission to Binary
      run: chmod +x dist/gitshield-cli

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        path: dist/gitshield-cli
        filename: dist/gitshield-cli-${{ matrix.os }}.zip

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        path: dist/gitshield-cli-${{ matrix.os }}.zip
